# Generated by Django 4.0.8 on 2022-12-20 11:18

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Movie title')),
                ('poster', models.URLField(verbose_name='Movie Poster')),
                ('summary', django_quill.fields.QuillField()),
                ('violence', django_quill.fields.QuillField()),
                ('violence_rating', models.IntegerField()),
                ('language', django_quill.fields.QuillField()),
                ('language_rating', models.IntegerField()),
                ('inappropriate', django_quill.fields.QuillField()),
                ('inappropriate_rating', models.IntegerField()),
                ('drug_usage', django_quill.fields.QuillField()),
                ('religious_imagery', django_quill.fields.QuillField()),
                ('duration', models.CharField(help_text='eg 2h 33m', max_length=10)),
            ],
        ),
    ]
