# Generated by Django 4.0.8 on 2022-12-21 10:37

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='kk', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
