# Generated by Django 4.0.8 on 2022-12-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(default='PG', help_text='movie rating (eg, PG, R Rated)', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2022),
            preserve_default=False,
        ),
    ]
